### ISSUE TITLE
I18N Self-Review

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#1349]
Short i18n review checklist is [here](http://w3c.github.io/i18n-activity/reviews/shortchecklist)

1. [x] _If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),_

    Comments go here.
    
2. [ ] _If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics._

    Comments go here.

3. [ ] _If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc._

    Comments go here.

4. [ ] _If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers_

    Comments go here.

5. [ ] _If the spec (or its implementation) sorts text_

    Comments go here.

6. [ ] _If the spec (or its implementation) captures user input_

    Comments go here.

7. [ ] _If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries_

    Comments go here.

8. [ ] _If the spec (or its implementation) allows any character encoding other than UTF-8._

    Comments go here.

9. [ ] _If the spec (or its implementation) defines markup._

    Comments go here.

10. [ ] _If the spec (or its implementation) deals with names, addresses, time & date formats, etc_

    Comments go here.

11. [ ] _If the spec (or its implementation) describes a format or data that is likely to need localization._

    Comments go here.

12. [ ] _If the spec (or its implementation) makes any reference to or relies on any cultural norms_

    Comments go here.

**Comment by Orhanoguz3567** [comment]
> Kısa i18n inceleme kontrol listesi [burada](http://w3c.github.io/i18n-activity/reviews/shortchecklist)
> 
> 1. [x]  _Spesifikasyonun (veya uygulanmasının) bir insan tarafından okunacak herhangi bir doğal dil metni içermesi durumunda (buna hata mesajları veya diğer kullanıcı arayüzü metinleri, JSON dizeleri vb. dahildir),_
>    Yorumlar buraya gelecek.
> 2. [ ]  _Spesifikasyonun (veya uygulanmasının), içerik yazarlarının kendi başına veya grafiklerle birlikte tipografik olarak çekici metinler üretmesine izin vermesi._
>    Yorumlar buraya gelecek.
> 3. [ ]  _Spesifikasyonun (veya uygulanmasının) kullanıcının metni işaret etmesine, metin parçaları oluşturmasına, metni birleştirmesine, kullanıcının metin seçmesine veya metin içinde adım atmasına (imleç veya başka yöntemler kullanarak) vb. izin vermesi durumunda._
>    Yorumlar buraya gelecek.
> 4. [ ]  _Spesifikasyon (veya uygulaması), sözdizimi ve tanımlayıcılar dahil olmak üzere metnin aranmasına veya eşleştirilmesine izin veriyorsa_
>    Yorumlar buraya gelecek.
> 5. [ ]  _Spesifikasyon (veya uygulaması) metni sıralıyorsa_
>    Yorumlar buraya gelecek.
> 6. [ ]  _Spesifikasyon (veya uygulaması) kullanıcı girişini yakalıyorsa_
>    Yorumlar buraya gelecek.
> 7. [ ]  _Spesifikasyonun (veya uygulanmasının), insanlar tarafından okunacak şekilde zamanla ilgili olması ve/veya zaman dilimi sınırlarını aşması durumunda_
>    Yorumlar buraya gelecek.
> 8. [ ]  _Spesifikasyon (veya uygulaması) UTF-8 dışında herhangi bir karakter kodlamasına izin veriyorsa._
>    Yorumlar buraya gelecek.
> 9. [ ]  _Spesifikasyon (veya uygulaması) işaretlemeyi tanımlıyorsa._
>    Yorumlar buraya gelecek.
> 10. [ ]  _Spesifikasyon (veya uygulanması) isimler, adresler, saat ve tarih formatları vb. ile ilgileniyorsa_
>     Yorumlar buraya gelecek.
> 11. [ ]  _Spesifikasyonun (veya uygulanmasının) yerelleştirme gerektirmesi muhtemel bir format veya veriyi tanımlaması durumunda._
>     Yorumlar buraya gelecek.
> 12. [ ]  _Spesifikasyonun (veya uygulanmasının) herhangi bir kültürel norma atıfta bulunması veya bunlara dayanması durumunda_
>     Yorumlar buraya gelecek.

👍🏻
